#!/bin/bash

THREADS="6"
DEVICE="mk908-defconfig"

# default toolchain
TOOLCHAIN=../../../prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi-

# linaro 4.8 toolchain
#TOOLCHAIN=../../../prebuilts/gcc/linux-x86/arm/android-toolchain-eabi/bin/arm-linux-androideabi-

if [ "$1" != "" ]; then
	THREADS="$1"
fi

if [ "$2" != "" ]; then
	DEVICE="$2"
fi

cp $DEVICE .config 
rm build.log
echo -e "\n==========================================="
echo -e " Configuring kernel for ${DEVICE}"
echo -e "===========================================\n"
ARCH=arm CROSS_COMPILE=$TOOLCHAIN make $DEVICE 

echo -e "\n==========================================="
echo -e " Building kernel for ${DEVICE} with ${THREADS} thread(s)"
echo -e "===========================================\n"
ARCH=arm CROSS_COMPILE=$TOOLCHAIN make -j$THREADS > build.log 2>&1
ARCH=arm CROSS_COMPILE=$TOOLCHAIN make -j$THREADS modules > build.log 2>&1

if [ -f ./arch/arm/boot/zImage ]
 then
  echo -e "\n==========================================="
  echo -e " Copying kernel/modules into rk3188 device directories"
  echo -e "===========================================\n"
  cp arch/arm/boot/zImage ../../../device/rockchip/rk3188/kernel
  find . -name "*.ko" -exec cp {} ../../../device/rockchip/rk3188/prebuilt/lib/modules \;
else 
  echo " No kernel/module found, stopping."
  exit 1
fi
