#
# $Header$
#
# $Date$
# $Revision$
# $Author$
#
# Copyright (C) 2009 Alex Buell <alex.buell@munted.org.uk>
# All Rights Reserved.
#

obj-$(CONFIG_EXFAT_FS) += exfat.o

exfat-y  := bitmap.o cache.o cluster.o dir.o fatent.o inode.o super.o upcase.o utils.o
